remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  
minima:
  skin: auto # switch with your system settings.

title: Analyzing the Relationship Between Olympic Medal Counts and National GDP

sass:
  load_paths:
    - _sass
    - assets/css

highlighter: rouge
